### ISSUE TITLE
Image links broken in GitHub repository

### ISSUE THREAD

**Issue by bontreger** [redhat-cop/automation-good-practices#46]
Image links are broken and need to be resolved.

**Comment by ericzolf** [comment]
It could definitely be better but it's definitely not broken, and the current situation is mostly due to asciidoctor and GitHub limitations: if you render the whole document, the rendering is done in the current directory (the root of the repo, where the main document lies) and the links are relative to this, and do work. But if you browse through GitHub (and I guess this is what you did), the links are relative to the current sub-document and hence wrong.

I keep the issue open, I'd also like to have something working under all conditions, but I didn't find a solution (yet).

Also the final rendering of the site at https://redhat-cop.github.io/automation-good-practices/ as described at the end of the CONTRIBUTE document is not really nice.
